Feat list
Minnesota-Computer-Club/MCC-Website pull request #35
Opened 2022-12-06 23:31 UTC by cursorweb

This will add lists for people who aren't in the form or aren't in the leaderboard (malformatted users)

2022-12-06 23:34 UTC, cursorweb commented
please don't merge yet

2022-12-06 23:43 UTC, cursorweb commented
okay i'll just remove reviewers

2022-12-07 00:12 UTC, cursorweb commented
fixes #35

2022-12-07 18:55 UTC, mike-weiner requested changes
I've left some comments throughout. Just a few things to clean up. I left a few comments on things that I was unsure about (Google Form links) that @jobartucz (or someone that knows) will need to answer.

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/index.js
> +import { NoForm } from './others/noform';
Do we need this import statements on this page? It doesn't look like they are being used.

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/index.js
> +                    <p><a href="./leaderboard/others">Click Here</a> for more.</p>
When testing locally, this link didn't always work for me - which is weird since the relative path is correct. 

I tried switching from using the `<a>` tag to the Next.js `<Link>` component to create the hyperlink, and things worked great. Can we make that switch here? It's a good practice to get into with Next.js anyways: https://nextjs.org/docs/messages/no-html-link-for-pages

If we were to make this a button that said `Find Out Why` or something like that, what does it look like?

<img width="382" alt="Screenshot-2022-12-07-12 45 30PM" src="https://user-images.githubusercontent.com/47571709/206269655-ee02d9a5-1c19-440f-9150-620bea1bca21.png">

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/others/index.js
> +                    <div>
Some padding for the text on this page to bring it away from the border of the screens would probably be nice as well. (See the screenshot in the comment above).

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/others/index.js
> +                    <p><Link href=".">Return</Link></p>
Can we make this a button or give it some more padding to kick it away from the paragraph above? Maybe instead of `Return` we can say `Return to Leaderboard`?

<img width="374" alt="Screenshot-2022-12-07-12 45 42PM" src="https://user-images.githubusercontent.com/47571709/206269107-0df1de45-cb86-4198-8e8e-a54a40da6320.png">

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/others/index.js
> +                                    <NoForm
I saw that there is an empty row at the bottom of this table with no name listed. Is this a bug or is there just no name listed on the account? 

<img width="371" alt="Screenshot-2022-12-07-12 45 59PM" src="https://user-images.githubusercontent.com/47571709/206269508-9060b92d-133e-4910-92d4-af69a7d7b393.png">

2022-12-07 18:55 UTC, mike-weiner commented on components/Leaderboard/others/index.js
> +                    <p>If you don&apos;t see yourself on the main leaderboard, you may have messed up the form. Please verify you completed the <Link href="https://forms.gle/4g9MYAjyY4KmnvEo9">form</
Can we have links to external sites (like the Google Form linked here) open up in a new tab?

I am not familiar with how the Google Form is set up. Is this the correct link for the MN-wide competition and do we display the correct link for the Rochester-only competition?

2022-12-07 18:55 UTC, mike-weiner commented on pages/wcc/leaderboard/others.js
> +            cookie: 'session=53616c7465645f5fe0bf9819378fb124702a5bed2ebf04b4cd64100945d041c919b74e0203f262ac15a5a85ea35664bc6f7f93f0c18ed8ab53f822a278ee0b9c',
Should this session token be stored in plain text? I wouldn't think so, but I could be wrong?

2022-12-07 18:55 UTC, mike-weiner commented on pages/rochester/wcc/leaderboard/others.js
> +            cookie: 'session=53616c7465645f5fe0bf9819378fb124702a5bed2ebf04b4cd64100945d041c919b74e0203f262ac15a5a85ea35664bc6f7f93f0c18ed8ab53f822a278ee0b9c',
Should this session token be stored in plain text? I wouldn't think so, but I could be wrong?

2022-12-07 22:33 UTC, cursorweb commented on components/Leaderboard/others/index.js
> +                                    <NoForm
it's not a bug they just don't have a name

2022-12-07 22:34 UTC, cursorweb commented on pages/rochester/wcc/leaderboard/others.js
> +            cookie: 'session=53616c7465645f5fe0bf9819378fb124702a5bed2ebf04b4cd64100945d041c919b74e0203f262ac15a5a85ea35664bc6f7f93f0c18ed8ab53f822a278ee0b9c',
that's for kenny to decide i just copied the same code from the other leaderboard

2022-12-07 22:34 UTC, cursorweb commented on pages/wcc/leaderboard/others.js
> +            cookie: 'session=53616c7465645f5fe0bf9819378fb124702a5bed2ebf04b4cd64100945d041c919b74e0203f262ac15a5a85ea35664bc6f7f93f0c18ed8ab53f822a278ee0b9c',
that's for kenny to decide i just copied the same code from the other leaderboard

2022-12-07 22:48 UTC, cursorweb commented on components/Leaderboard/others/index.js
> +                    <p><Link href=".">Return</Link></p>
done

2022-12-07 22:51 UTC, cursorweb commented on components/Leaderboard/others/index.js
> +                    <p>If you don&apos;t see yourself on the main leaderboard, you may have messed up the form. Please verify you completed the <Link href="https://forms.gle/4g9MYAjyY4KmnvEo9">form</
yep, a tiny oversight,

2022-12-07 23:07 UTC, cursorweb commented on components/Leaderboard/index.js
> +                    <p><a href="./leaderboard/others">Click Here</a> for more.</p>
actually on second thought
![image](https://user-images.githubusercontent.com/29520825/206316500-a244c7f0-e424-41e2-b297-9f49c658bae8.png)


i'm using it

2022-12-08 05:09 UTC, jobartucz approved these changes
Looks good now

2022-12-08 05:11 UTC, jobartucz commented
Looks good to me.

2022-12-08 05:12 UTC, merged

2022-12-08 19:50 UTC, cursorweb commented
thanks!