Feat hover effects
Minnesota-Computer-Club/MCC-Website pull request #49
Opened 2022-12-14 23:35 UTC by cursorweb

This lets people view their individual team members

I'm not sure if people want to see how many stars each individual team member has, but that's whatever. Make another issue, I'll take a look.

fixes an old #9

2022-12-15 01:45 UTC, mike-weiner commented on components/Leaderboard/teams/index.js
> +                        {members.map((x, i) => <p key={i}>{x.name}</p>)}
I believe this might be causing a DOM error since this nests a `<p>` inside of a `<p>`. 

You might be able to change this line to `{members.map((x, i) => <div key={i}>{x.name}</div>)}` and then use some CSS to break each name out onto its own line.

2022-12-15 01:46 UTC, mike-weiner requested changes
Everything seems to be working good - except for that pesky DOM error. Nice work!

2022-12-15 01:46 UTC, mike-weiner commented on components/Leaderboard/teams/index.js
> +                        {members.map((x, i) => <p key={i}>{x.name}</p>)}
<img width="1259" alt="Screenshot-2022-12-14-07 44 24PM" src="https://user-images.githubusercontent.com/47571709/207753085-ff65e8df-f642-4fad-9f96-276fe94b0dcf.png">

2022-12-16 04:43 UTC, cursorweb commented on components/Leaderboard/teams/index.js
> +                        {members.map((x, i) => <p key={i}>{x.name}</p>)}
I didn't notice that, oops!

The `<p>` had a functionality of a `<div>` tag so it would be good anyways

2022-12-16 13:53 UTC, mike-weiner commented
Turns out `<div>` cannot appear as children of `<p>` because `<p>` can only have children that are inline elements. I learn something new every day. 

https://stackoverflow.com/questions/8397852/why-cant-the-p-tag-contain-a-div-tag-inside-it

I just went in and did some switching to avoid those DOM errors.

2022-12-16 13:54 UTC, mike-weiner approved these changes
Revisions look great. Nice work!

2022-12-16 20:16 UTC, merged

2022-12-16 20:16 UTC, cursorweb commented
Thanks!